# Single dimensional

In [3]:
import numpy as np
b=np.array((1,5,6,7))
print(b)

[1 5 6 7]


# Multi dimentional

In [4]:
import numpy as np
b=np.array([(1,5,6,7),(2,4,5,9)])
print(b)

[[1 5 6 7]
 [2 4 5 9]]


# Range of values in array

In [7]:
c=np.arange(10)  #range of values in array
d=np.linspace(1,5,6)  #set of values by interval
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


# Properties of array

In [8]:
a=np.array((1,5,6,7))
b=np.array([(1,5,6,7),(2,4,5,9)])
print(a.ndim)  # Dimension of array
print(a.itemsize)   #Byte sizee of each element
print(a.dtype)   # Datatype of array
print(a.size*a.itemsize)  #memory occupied - space occupied by 1
print(a.size)  #number of elments in array
print(b.shape)  # shape of array(rows and columns)

1
4
int32
16
4
(2, 4)


# Reshape array

In [10]:
print("before")
b=np.array([(1,5,6,7),(2,4,5,9)])
print(b)
print("after")
b=b.reshape(4,2)
print(b)

before
[[1 5 6 7]
 [2 4 5 9]]
after
[[1 5]
 [6 7]
 [2 4]
 [5 9]]


# Array Slicing

In [11]:
b=np.array([(1,5,6,7),(2,4,5,9)])
print(b[0,2]) #slicing the element from certain row and column
print(b[0:,2]) #slicing element from all rows and certain column

6
[6 5]


# Array max ,min, sum finding

In [12]:
e=np.array([7,9,9,3,45,7,23])
print(e.min())  # returns min value
print(e.max())  # returns max value
print(e.sum())  # returns sum value of numpy

3
45
103


# Arithematic operation

In [15]:
a=np.array((7,9,9,2))
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0)) #Each elemnet of 1st dim array with same index with another dim element
print(b.sum(axis=1)) #sum of all element is 1st dim and sum of all elemnet is 2nd dim
print(np.sqrt(a))  # squareroot
print(np.std(a))   #standard deviation
print(np.exp(a))   #Exponential of array
print(np.log(a))   #Natural log-ln
print(np.log10(a))  #log base 10

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [18]:
b=np.array([(7,9,9,2),(16,11,9,6)])
f=np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f)))  #Vertical Stack
print("---------")
print(np.hstack((b,f)))  #Horizonatl Stack
print("---------")
print(b.ravel())         #Merging as a single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
---------
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
---------
[ 7  9  9  2 16 11  9  6]


# Three Dimentional Array

In [20]:
threeDArray=np.array([
    [[1,2,3],[4,5,6]],
    [[-1,-2,-3],[-4,-5,-6]]
])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [27]:
print(threeDArray.shape)
print(threeDArray.size)
print(threeDArray.dtype)
print(threeDArray.ndim)
print(threeDArray.itemsize)

(2, 2, 3)
12
int32
3
4


In [30]:
for i in threeDArray.flatten():   #convert any dimention to single dimension use flatten
    print(i)
print("another Method")
print(threeDArray.ravel())

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6
another Method
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]


# Filling array with specific values

In [31]:
# zeros
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [32]:
#ones
ones=np.ones(5)
print(ones)        # this is in float

[1. 1. 1. 1. 1.]


In [33]:
ones=ones.astype(int)
print(ones)        # type cast and make it to int

[1 1 1 1 1]


In [35]:
#arange
ranges=np.arange(5.6,9.8)
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [37]:
#linespace
linespace=np.linspace(3,6,10)
print(linespace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


# Scalar operations

In [40]:
matrix=np.array([[6,34,89],[23,34,45]])
print(matrix)

[[ 6 34 89]
 [23 34 45]]


In [41]:
print(matrix+2)

[[ 8 36 91]
 [25 36 47]]


In [42]:
# it does not work on list
pythonlist=[[6,34,89],[23,34,45]]
print(pythonlist * 2)   

[[6, 34, 89], [23, 34, 45], [6, 34, 89], [23, 34, 45]]


In [43]:
#Transpose
print(matrix.T)

[[ 6 23]
 [34 34]
 [89 45]]


In [44]:
print(matrix[1,]) 

[23 34 45]


In [45]:
print("1 dimesion")
full=np.full(10,5)
print(full)
print("2 dimesion")
full=np.full((2,2),10)
print(full)
print("3 dimesion")
full=np.full((2,5,4),5)
print(full)


1 dimesion
[5 5 5 5 5 5 5 5 5 5]
2 dimesion
[[10 10]
 [10 10]]
3 dimesion
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


# Element wise operations

In [62]:
pythonlist1=[[76,34,89],[23,34,45]]
pythonlist2=[[76,34,89],[23,34,45]]

In [48]:
pythonlist1+pythonlist2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [63]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[7,8,9],[10,11,12],[7,8,9]])

In [53]:
print(matrix1+matrix2)
print()
print(matrix1-matrix2)
print()
print(matrix1*matrix2)

[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]


In [64]:
print(np.matmul(matrix1, matrix2))

[[ 48  54  60]
 [120 135 150]
 [192 216 240]]


# Stastical function in Numpy

In [65]:
marks=np.array([
    [76,34,89],[23,34,45],
    [76,34,89],[23,34,45]
])

In [67]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())

23
89
602
50.166666666666664
24.02371513502624


In [68]:
print(marks.min(axis=1))  # axis 1 means rowwise
print(marks.max(axis=1))   # axis 2 means column wise
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))


[34 23 34 23]
[89 45 89 45]
[199 102 199 102]
[66.33333333 34.         66.33333333 34.        ]
[23.47102232  8.98146239 23.47102232  8.98146239]


In [69]:
# append
x=np.array([0,1,2,3,4])
y=np.array([5,6,7,8,9])
z=np.array([10,11,12,13,14])


In [70]:
np.hstack([x,y,z])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
np.vstack([x,y,z])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
np.append(x,(2,3))   # returns new array it does not append

array([0, 1, 2, 3, 4, 2, 3])

In [74]:
new_array=np.array([1,2,3])

In [75]:
x=np.append([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

In [76]:
np.transpose(x)    # fun of np

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [77]:
x.T      # using obj for x

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

# Boolean Indexing

In [78]:
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [79]:
arr > 4

array([False, False, False, False, False,  True,  True])

In [80]:
arr[arr > 4]

array([5, 6])

In [83]:
array=np.arange(12)

In [85]:
array.shape =(3,4)

In [84]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# Generating random values

In [86]:
np.random.rand(5)

array([0.03752308, 0.68215547, 0.20342572, 0.14239512, 0.99477204])

In [87]:
#generating random matrix
np.random.randint(10,20,(5,5))  # start value,stop value,shape

array([[13, 15, 14, 13, 10],
       [13, 11, 10, 16, 19],
       [13, 19, 15, 10, 16],
       [14, 19, 11, 17, 19],
       [17, 11, 15, 13, 17]])

In [89]:
letters=list('aeiou')
np.random.choice(letters,13)

array(['a', 'a', 'e', 'i', 'i', 'i', 'i', 'a', 'e', 'e', 'e', 'u', 'u'],
      dtype='<U1')

In [90]:
np.random.choice(letters,5,replace=False)   # same letters wont repeat

array(['u', 'i', 'e', 'a', 'o'], dtype='<U1')

In [92]:
np.random.choice(letters,15,p=[0.4,0.3,0.1,0.1,0.1])

array(['u', 'e', 'a', 'u', 'e', 'a', 'e', 'e', 'e', 'a', 'e', 'e', 'a',
       'a', 'e'], dtype='<U1')

# Save and Load array

In [93]:
array=np.random.randint(10,20,(5,5))
np.save('array_file',array)

In [94]:
array2=np.load('array_file.npy')
print(array2)

[[13 17 13 13 18]
 [12 11 15 19 11]
 [17 12 19 16 10]
 [13 10 16 13 14]
 [17 16 17 13 17]]
